import { Instance } from "mobx-state-tree"
import { DeletePostPayloadModelBase } from "./DeletePostPayloadModel.base"

/* The TypeScript type of an instance of DeletePostPayloadModel */
export interface DeletePostPayloadModelType extends Instance<typeof DeletePostPayloadModel.Type> {}

/* A graphql query fragment builders for DeletePostPayloadModel */
export { selectFromDeletePostPayload, deletePostPayloadModelPrimitives, DeletePostPayloadModelSelector } from "./DeletePostPayloadModel.base"

/**
 * DeletePostPayloadModel
 *
 * Autogenerated return type of DeletePost
 */
export const DeletePostPayloadModel = DeletePostPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
